services:
  zoom-translation-server:
    build: ./zoom-translation-server
    pull_policy: build
    container_name: zoom-translation-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APPID=${APPID}
      - APISECRET=${APISECRET}
      - APIKEY=${APIKEY}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - OLLAMA_URL=${OLLAMA_URL}
      - DEBUG_MODE=${DEBUG_MODE}
    networks:
      - zoom-translation

  zoom-rtms-server:
    build: ./zoom-rtms-server
    pull_policy: build
    container_name: zoom-rtms-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ZM_RTMS_CLIENT=${ZM_RTMS_CLIENT}
      - ZM_RTMS_SECRET=${ZM_RTMS_SECRET}
      - TRANSCRIPTION_SERVER_URL=${TRANSCRIPTION_SERVER_URL}
    depends_on:
      - zoom-translation-server
    networks:
      - zoom-translation

networks:
  zoom-translation:
    driver: bridge
