services:
  zoom-rtms-server:
    build: ./zoom-rtms-server
    pull_policy: build
    container_name: zoom-rtms-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ZM_RTMS_CLIENT=${ZM_RTMS_CLIENT}
      - ZM_RTMS_SECRET=${ZM_RTMS_SECRET}
      - TRANSCRIPTION_SERVER_URL=${TRANSCRIPTION_SERVER_URL}
    depends_on:
      - backend
      - frontend
    networks:
      - zoom-translation

  frontend:
    build: ./frontend
    pull_policy: build
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4173:4173"
    depends_on:
      - backend
    networks:
      - zoom-translation

  backend:
    build: ./backend
    pull_policy: build
    container_name: backend
    restart: unless-stopped
    ports:
      - "8001:8000"
    environment:
      - APPID=${APPID}
      - APISECRET=${APISECRET}
      - APIKEY=${APIKEY}
      - DASHSCOPE_API_KEY=${DASHSCOPE_API_KEY}
      - DEBUG_MODE=${DEBUG_MODE}
    # depends_on:
    #   - ollama
    networks:
      - zoom-translation

#   ollama:
#     image: ollama/ollama
#     container_name: ollama
#     restart: unless-stopped
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama_data:/root/.ollama
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: 1
#               capabilities: [gpu]
#     networks:
#       - zoom-translation
#
# volumes:
#   ollama_data:

networks:
  zoom-translation:
    driver: bridge
