import { drizzle } from "drizzle-orm/bun-sql";
import { migrate } from "drizzle-orm/bun-sql/migrator";
import { env } from "./config";

// Initialize the database connection using Bun's native SQL driver
export const db = drizzle(env.DATABASE_URL);

// TODO:
// Automatically handle migrations on startup

// This looks for the migration files generated by Drizzle Kit in the "./drizzle" folder
// async function runMigrations() {
//   console.log("Checking for database migrations...");
//   try {
//     await migrate(db, { migrationsFolder: "./drizzle" });
//     console.log("Database migrations applied successfully.");
//   } catch (error) {
//     console.error("Migration failed:", error);
//     // If migrations fail, we usually want to kill the app rather than run in an unstable state
//     process.exit(1);
//   }
// }
// Execute the migrations
// await runMigrations();
