import { drizzle } from "drizzle-orm/bun-sql";
import { migrate } from "drizzle-orm/bun-sql/migrator";
import { env } from "./config";
import { sql } from "drizzle-orm";
import { logger } from "./logger";

// Initialize the database connection using Bun's native SQL driver
export const db = drizzle(env.DATABASE_URL);

// Test Database Connection
export async function testDbConnection() {
  try {
    // A simple query to check if the database is responding
    await db.execute(sql`SELECT 1`);
    logger.info("Database connection verified.");
  } catch (error) {
    logger.error("Database connection failed.", { error });
    process.exit(1);
  }
}

// Automatically handle migrations on startup
export async function runMigrations() {
  try {
    // This looks for the migration files generated by Drizzle Kit in the "./drizzle" folder
    await migrate(db, { migrationsFolder: "./drizzle" });
    logger.info("Database migrations applied successfully.");
  } catch (error) {
    logger.error("Database migration failed.", { error });
    // Kill the app rather than run in an unstable state with mismatched schemas
    process.exit(1);
  }
}
