import { SignJWT, jwtVerify } from "jose";
import { env } from "../core/config";

// Ensure you have a strong secret in your .env file
const JWT_SECRET = new TextEncoder().encode(env.JWT_SECRET);

/**
 * Generates a standard JWT for API authentication.
 * You can store this in an HTTP-only cookie.
 */
export async function generateApiSessionToken(
  userId: string,
  tenantId: string,
): Promise<string> {
  return await new SignJWT({ userId, tenantId })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("7d") // 1 week expiration for the main session
    .sign(JWT_SECRET);
}

/**
 * Generates a short-lived, single-use JWT for WebSocket authentication.
 */
export async function generateWsTicket(
  userId: string,
  tenantId: string,
): Promise<string> {
  return await new SignJWT({ userId, tenantId, purpose: "websocket_ticket" })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("30s") // Extremely short-lived; just long enough to connect
    .sign(JWT_SECRET);
}

/**
 * Verifies and decodes any JWT generated by this utility.
 */
export async function verifyToken(token: string) {
  try {
    const { payload } = await jwtVerify(token, JWT_SECRET);
    return payload;
  } catch (error) {
    return null; // Token is invalid or expired
  }
}

/**
 * Helper to standardise setting secure, HTTP-only session cookies in Elysia.
 */
export function setSessionCookie(cookieRef: any, token: string) {
  cookieRef.set({
    value: token,
    httpOnly: true,
    secure: env.NODE_ENV === "production",
    sameSite: "lax", // Protects against CSRF while allowing standard navigation
    path: "/",
    maxAge: 60 * 60 * 24 * 7, // 7 days (matches the API session token)
  });
}

/**
 * Helper to clear the session cookie on logout.
 */
export function clearSessionCookie(cookieRef: any) {
  cookieRef.set({
    value: "",
    httpOnly: true,
    secure: env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 0, // Immediately expire the cookie
  });
}
