import { SignJWT, jwtVerify } from "jose";
import { env } from "../core/config";
import { logger } from "../core/logger";

/**
 * Shared signing secret for API sessions and short-lived WebSocket tickets.
 */
const JWT_SECRET = new TextEncoder().encode(env.JWT_SECRET);

/**
 * Generates the primary API session token stored in the auth cookie.
 */
export async function generateApiSessionToken(
  userId: string,
  tenantId: string,
): Promise<string> {
  return await new SignJWT({ userId, tenantId })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("7d")
    .sign(JWT_SECRET);
}

/**
 * Generates a short-lived, single-use JWT for WebSocket authentication.
 */
export async function generateWsTicket(
  userId: string,
  tenantId: string,
): Promise<string> {
  return await new SignJWT({ userId, tenantId, purpose: "websocket_ticket" })
    .setProtectedHeader({ alg: "HS256" })
    .setIssuedAt()
    .setExpirationTime("30s")
    .sign(JWT_SECRET);
}

/**
 * Verifies and decodes any JWT generated by this utility.
 */
export async function verifyToken(token: string) {
  try {
    const { payload } = await jwtVerify(token, JWT_SECRET);
    return payload;
  } catch (error) {
    logger.debug("Token verification failed.", { error });
    return null;
  }
}

/**
 * Helper to standardise setting secure, HTTP-only session cookies in Elysia.
 */
export function setSessionCookie(cookieRef: any, token: string) {
  cookieRef.set({
    value: token,
    httpOnly: true,
    secure: env.NODE_ENV === "production",
    // `lax` protects normal navigation flows while still reducing CSRF risk.
    sameSite: "lax",
    path: "/",
    maxAge: 60 * 60 * 24 * 7,
  });
}

/**
 * Helper to clear the session cookie on logout.
 */
export function clearSessionCookie(cookieRef: any) {
  cookieRef.set({
    value: "",
    httpOnly: true,
    secure: env.NODE_ENV === "production",
    sameSite: "lax",
    path: "/",
    maxAge: 0,
  });
}
